name: Deploy Outreach

on:
  push:
    branches:
      - master
    paths:
      - "apps/operations/**"
      - "packages/shared/**"
      - ".github/workflows/deploy-ops.yaml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Load Environment Variables
        run: |
          echo "${{ secrets.OPS_ENV }}" > apps/operations/.env

      - name: Build
        run: bun run build --filter=@melinia/operations

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        run: |
          aws s3 sync apps/operations/dist s3://${{ secrets.S3_OPS }} --delete --exclude "*.html" --cache-control "public, max-age=31536000, immutable"
          aws s3 sync apps/operations/dist s3://${{ secrets.S3_OPS }} --exclude "*" --include "*.html" --cache-control "public, max-age=0, must-revalidate"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.OPS_DIST_ID }} --paths "/*"
